### ISSUE TITLE
No way on Home Assistant

### ISSUE THREAD

**Issue by Noneofinterest** [rhasspy/rhasspy-junior#4]
No way to make Rhasspy work on Hassio.
3 months studying it and worth nothing.
I'll wait for someone to make an easy and more comprehensible (for non devs) instruction manual on how to install and setup Rhasspy on Home Assistant.
Please take also care of non developers customers.
Thank you for your effort.

**Comment by alexboss** [comment]
You're a bit harsh over Rhasspy. Tried the junior version and it worked like a charm. Now can't wait to try the expert version.
Check this video, it was really useful for me: https://youtu.be/BLJR_v3IFwk
